version: "2"
services: 
  web: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./node_modules/.bin/nodemon server.js
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:3000
  postgres:
    image: kiasaki/alpine-postgres
    environment:
      - POSTGRES_PASSWORD=heyman
      - POSTGRES_DB=dockertest
    ports:
      - 5432:5432